  ;output:5 0 8



 ;DS WILL ONLY USE FOR DATA SEGMENT
 ;SS USED FOR MEMORY
 ;FOR SPACE DECLARE 32


.MODEL SMALL ;MEMORY DECLARATION SEGMENT
.STACK 100H

.DATA ;DATA SEGMENT

    ;VARIABLE DECLARATION PART

    SPACE DB 32
    NUM DB 53;NUM VAR-NAME VALUE
    NUM2 DB 48
    NUM3 DB 56
    ;MSG DB "HELLO WORLD! $" ;MSG = VARIABLENAME, DB = DEFINE BYTE/DW=DEFINE WORD  
    
    
.CODE ;CODE SEGMENT
    
    MAIN PROC ;MAIN PROCESS
        
              ;CODING METHODS INSTRUCTION(ADD,DIV,MUL,SUB) DESTINATION,SOURCE 
              ;BELOW CODE AX WILL STORE ALL VARIABLE FROM DATA BY INVITING ,THEN AX AGAIN TAKE ALL THE VALUE TO DS
                
        
        MOV AX,@DATA ;BY GIVING MOV AX @DATA WE ARE INVITING POINTING TO .DATA, HERE AX IS GENERAL PURPOSE REGISTER
        MOV DS,AX  ; DS GENERALY POINTS AT SEGMENT WHERE VARIABLE ARE DEFINED
        MOV AH,2
        
        
        MOV DL,NUM ;THIS WILL PRINT NUM 53 AS ASCII VALUE 5
        INT 21H
        
        MOV DL,SPACE ;THIS WILL PROVIDE SPACE
        INT 21H
        
        MOV DL,NUM2 ;THIS WILL PRINT NUM2 AS ASCII VALUE 0
        INT 21H
        
        MOV DL,SPACE  ;THIS WILL PROVIDE SPACE
        INT 21H
        
        MOV DL,NUM3  ;THIS WILL PRINT NUM3 AS ASCII VALUE 8
        INT 21H
        
    MOV AH,4CH ;IT IS LIKE RETURN 0, WE HAVE TO WRITEMOV BEFORE GIVING ANY INSTRUCTION
    INT 21H
    MAIN ENDP
    
END MAIN
        

    